package: cache_warm_up
version: '0.0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/cache_warm_up


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.13



page:
    title: translate:cache_warm_up_title
    prio: 100
    icon: rex-icon fa-gear

pages:
    system/cache_warm_up:
        title: translate:cache_warm_up_title
        icon: rex-icon fa-gear
        perm: cache_warm_up[]

default_config:
    field: 'Test'
